import { ALL_ERROR_CODES } from "./errors.js";
import { MessageTypes } from "./messages.js";
import { PROTOCOL_VERSION } from "./version.js";

/** Stable fixture corpus for cross-language conformance testing.
 *
 * The committed JSON file is generated by scripts/generate-fixtures.mjs and
 * MUST NOT be edited by hand. Independent implementations assert their
 * encoder/decoder against it.
 */
export const FIXTURES_VERSION = 1;

export interface FixtureCase {
  name: string;
  obj: unknown;
  canonical: string;
  frame_hex: string;
}

export function sampleMessages(): Array<{ name: string; obj: Record<string, unknown> }> {
  return [
    {
      name: "request",
      obj: { v: PROTOCOL_VERSION, t: MessageTypes.REQ, i: "AAAAAAAAAAAAAAAA", m: "echo", p: { hello: "world", n: 42 } }
    },
    {
      name: "response",
      obj: { v: PROTOCOL_VERSION, t: MessageTypes.RES, i: "AAAAAAAAAAAAAAAA", p: { echoed: true } }
    },
    {
      name: "error",
      obj: {
        v: PROTOCOL_VERSION,
        t: MessageTypes.ERR,
        i: "AAAAAAAAAAAAAAAA",
        e: { code: ALL_ERROR_CODES[0], message: "boom" }
      }
    },
    {
      name: "chunk-binary",
      obj: {
        v: PROTOCOL_VERSION,
        t: MessageTypes.CHUNK,
        i: "AAAAAAAAAAAAAAAA",
        n: 0,
        d: { $b: true, c: "application/octet-stream", d: "AQIDBA==" }
      }
    },
    {
      name: "end",
      obj: { v: PROTOCOL_VERSION, t: MessageTypes.END, i: "AAAAAAAAAAAAAAAA", p: { total: 3 } }
    },
    {
      name: "event",
      obj: { v: PROTOCOL_VERSION, t: MessageTypes.EVT, s: "BBBBBBBBBBBB", e: "tasks.status", p: { pct: 50 } }
    },
    {
      name: "subscribe",
      obj: { v: PROTOCOL_VERSION, t: MessageTypes.SUB, s: "BBBBBBBBBBBB", e: "tasks.status" }
    },
    {
      name: "cancel",
      obj: { v: PROTOCOL_VERSION, t: MessageTypes.CANCEL, i: "AAAAAAAAAAAAAAAA" }
    },
    {
      name: "ping",
      obj: { v: PROTOCOL_VERSION, t: MessageTypes.PING, ts: 1700000000000 }
    }
  ];
}
