/** Shared signaling state and node-to-node delivery for horizontal scale-out. */
export interface DistributedPresence<TPresence = Record<string, unknown>> {
  route: string;
  presence: TPresence;
}

export interface DistributedPair<TPresence = Record<string, unknown>>
  extends DistributedPresence<TPresence> {
  psid: string;
}

export interface BackplaneDelivery {
  to: string;
  from: string;
  blob: string;
}

export interface SignalingBackplane<TPresence = Record<string, unknown>> {
  readonly kind: string;
  connect(): Promise<void>;
  putPresence(appId: string, value: DistributedPresence<TPresence>, ttlMs: number): Promise<void>;
  getPresence(appId: string): Promise<DistributedPresence<TPresence> | null>;
  listPresence(): Promise<Array<DistributedPresence<TPresence>>>;
  deletePresence(appId: string, route: string): Promise<void>;
  putPair(codeHash: string, value: DistributedPair<TPresence>, ttlMs: number): Promise<void>;
  getPair(codeHash: string): Promise<DistributedPair<TPresence> | null>;
  publish(nodeId: string, delivery: BackplaneDelivery): Promise<void>;
  subscribe(nodeId: string, onDelivery: (delivery: BackplaneDelivery) => void): Promise<void>;
  close(): Promise<void>;
}

/**
 * Redis implementation. Pair codes and presence use TTL keys; opaque pairing
 * payloads use pub/sub and are never retained. `nodeId` is generated by the
 * signaling process and carries no user identity.
 */
export class RedisSignalingBackplane<TPresence = Record<string, unknown>>
  implements SignalingBackplane<TPresence>
{
  readonly kind = "redis";
  private command?: import("redis").RedisClientType;
  private subscriber?: import("redis").RedisClientType;

  constructor(
    private readonly url: string,
    private readonly namespace = "crosslink:signal"
  ) {}

  async connect(): Promise<void> {
    const { createClient } = await import("redis");
    const command = createClient({ url: this.url });
    command.on("error", () => {
      // Individual operations reject with the useful error. An EventEmitter
      // error listener is still required so a Redis outage cannot crash Node.
    });
    await command.connect();
    const subscriber = command.duplicate();
    subscriber.on("error", () => {});
    await subscriber.connect();
    this.command = command as import("redis").RedisClientType;
    this.subscriber = subscriber as import("redis").RedisClientType;
  }

  async putPresence(
    appId: string,
    value: DistributedPresence<TPresence>,
    ttlMs: number
  ): Promise<void> {
    await this.requiredCommand().set(this.presenceKey(appId), JSON.stringify(value), { PX: ttlMs });
    await this.requiredCommand().sAdd(this.presenceIndexKey(), appId);
  }

  async getPresence(appId: string): Promise<DistributedPresence<TPresence> | null> {
    return this.read<DistributedPresence<TPresence>>(this.presenceKey(appId));
  }

  async listPresence(): Promise<Array<DistributedPresence<TPresence>>> {
    const command = this.requiredCommand();
    const appIds = await command.sMembers(this.presenceIndexKey());
    if (appIds.length === 0) return [];
    const raw = await command.mGet(appIds.map((appId) => this.presenceKey(appId)));
    const out: Array<DistributedPresence<TPresence>> = [];
    const stale: string[] = [];
    raw.forEach((entry, index) => {
      if (!entry) {
        stale.push(appIds[index]);
        return;
      }
      try {
        out.push(JSON.parse(entry) as DistributedPresence<TPresence>);
      } catch {
        stale.push(appIds[index]);
      }
    });
    if (stale.length > 0) await command.sRem(this.presenceIndexKey(), stale);
    return out;
  }

  async deletePresence(appId: string, route: string): Promise<void> {
    const current = await this.getPresence(appId);
    if (!current || current.route !== route) return;
    await this.requiredCommand().del(this.presenceKey(appId));
    await this.requiredCommand().sRem(this.presenceIndexKey(), appId);
  }

  async putPair(
    codeHash: string,
    value: DistributedPair<TPresence>,
    ttlMs: number
  ): Promise<void> {
    await this.requiredCommand().set(this.pairKey(codeHash), JSON.stringify(value), { PX: ttlMs });
  }

  getPair(codeHash: string): Promise<DistributedPair<TPresence> | null> {
    return this.read<DistributedPair<TPresence>>(this.pairKey(codeHash));
  }

  async publish(nodeId: string, delivery: BackplaneDelivery): Promise<void> {
    await this.requiredCommand().publish(this.nodeChannel(nodeId), JSON.stringify(delivery));
  }

  async subscribe(
    nodeId: string,
    onDelivery: (delivery: BackplaneDelivery) => void
  ): Promise<void> {
    const subscriber = this.subscriber;
    if (!subscriber) throw new Error("Redis signaling backplane is not connected");
    await subscriber.subscribe(this.nodeChannel(nodeId), (raw) => {
      try {
        const delivery = JSON.parse(raw) as BackplaneDelivery;
        if (
          typeof delivery.to === "string" &&
          typeof delivery.from === "string" &&
          typeof delivery.blob === "string"
        ) {
          onDelivery(delivery);
        }
      } catch {
        // Ignore malformed messages from another namespace publisher.
      }
    });
  }

  async close(): Promise<void> {
    const subscriber = this.subscriber;
    const command = this.command;
    this.subscriber = undefined;
    this.command = undefined;
    await Promise.all([
      subscriber?.isOpen ? subscriber.quit() : Promise.resolve(),
      command?.isOpen ? command.quit() : Promise.resolve()
    ]);
  }

  private requiredCommand(): import("redis").RedisClientType {
    if (!this.command) throw new Error("Redis signaling backplane is not connected");
    return this.command;
  }

  private async read<T>(key: string): Promise<T | null> {
    const raw = await this.requiredCommand().get(key);
    if (!raw) return null;
    try {
      return JSON.parse(raw) as T;
    } catch {
      return null;
    }
  }

  private presenceKey(appId: string): string {
    return `${this.namespace}:presence:${encodeURIComponent(appId)}`;
  }
  private presenceIndexKey(): string {
    return `${this.namespace}:presence:index`;
  }
  private pairKey(codeHash: string): string {
    return `${this.namespace}:pair:${codeHash}`;
  }
  private nodeChannel(nodeId: string): string {
    return `${this.namespace}:node:${nodeId}`;
  }
}
