/**
 * Crosslink Service Worker Template & Generator
 *
 * Implements the framework-level offline shell caching strategy:
 * - Caches the minimum bootstrap shell (HTML, JS, CSS, manifest, icons)
 * - Network-first for navigation requests with fallback to cached shell on offline/timeout
 * - Cache-first with network fallback for static shell assets
 * - Strictly excludes API, RPC, WebSocket, and pairing/auth endpoints from caching
 * - Versioned cache namespaces with automatic cleanup of old caches
 */

export interface ServiceWorkerConfig {
  /** Cache version - increment to invalidate old caches */
  version: string;
  /** Assets to precache - the minimum shell for offline launch */
  precacheAssets: string[];
  /** Maximum navigation wait before showing the cached reconnect shell. */
  navigationTimeoutMs?: number;
}

export const DEFAULT_SERVICE_WORKER_CONFIG: ServiceWorkerConfig = {
  version: "2.0.0",
  precacheAssets: [
    "./mobile.html",
    "./bundle.js",
    "./manifest.webmanifest",
    "./crosslink-mark.svg",
    "./icon-192.png",
    "./icon-512.png"
  ],
  navigationTimeoutMs: 4_000
};

/**
 * Generate the standalone Service Worker JavaScript code.
 */
export function generateServiceWorker(config: Partial<ServiceWorkerConfig> = {}): string {
  const version = config.version || DEFAULT_SERVICE_WORKER_CONFIG.version;
  const precacheAssets = config.precacheAssets || DEFAULT_SERVICE_WORKER_CONFIG.precacheAssets;
  const navigationTimeoutMs = config.navigationTimeoutMs ?? DEFAULT_SERVICE_WORKER_CONFIG.navigationTimeoutMs ?? 4_000;
  const cacheName = `crosslink-shell-v${version}`;
  const assetsJson = JSON.stringify(precacheAssets, null, 2);

  return `/* Crosslink PWA Service Worker — Generated by Crosslink Framework */
const CACHE_NAME = "${cacheName}";
const PRECACHE_ASSETS = ${assetsJson};
const NAVIGATION_TIMEOUT_MS = ${navigationTimeoutMs};

// Endpoints and patterns that must NEVER be cached (security, credentials, active RPC/presence)
const NEVER_CACHE_PATTERNS = [
  "/api/",
  "/rpc/",
  "/ws",
  "/pair",
  "/verify-pair",
  "/challenge",
  "/session",
  "/__crosslink/install/",
  "/revoke",
  "/events"
];

function isSecuritySensitive(url) {
  const path = url.pathname;
  return NEVER_CACHE_PATTERNS.some((pattern) => path.includes(pattern));
}

async function fetchNavigation(request) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), NAVIGATION_TIMEOUT_MS);
  try {
    const response = await fetch(request, { signal: controller.signal });
    if (!response || !response.ok) throw new Error("host navigation unavailable");
    return response;
  } finally {
    clearTimeout(timeout);
  }
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(async (cache) => {
      // Robust asset caching: fetch individually so one missing asset doesn't abort entire install
      for (const asset of PRECACHE_ASSETS) {
        try {
          const res = await fetch(asset, { cache: "no-cache" });
          if (res.ok) {
            await cache.put(asset, res);
          }
        } catch (err) {
          console.warn("[Crosslink SW] Precache missed:", asset);
        }
      }
    })
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key.startsWith("crosslink-") && key !== CACHE_NAME)
          .map((key) => caches.delete(key))
      )
    ).then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  // Ignore cross-origin requests
  if (url.origin !== self.location.origin) return;

  // Never cache auth or API calls
  if (isSecuritySensitive(url)) {
    return;
  }

  // Install-specific manifests and bootstrap navigations carry only an opaque
  // handoff id, but serving a cached response for another install would still
  // lose or cross-wire the handoff. Always go to the network for them.
  if (url.searchParams.has("crosslink_install")) {
    event.respondWith(fetch(request, { cache: "no-store" }));
    return;
  }

  // 1. Navigation requests: network-first with offline fallback to cached shell
  if (request.mode === "navigate") {
    event.respondWith(
      fetchNavigation(request)
        .then((response) => {
          if (response && response.ok) {
            const copy = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(async () => {
          // Host is offline: return cached shell
          const cached =
            (await caches.match(request, { ignoreSearch: true })) ||
            (await caches.match("./mobile.html", { ignoreSearch: true })) ||
            (await caches.match("/mobile.html", { ignoreSearch: true })) ||
            (await caches.match("/", { ignoreSearch: true }));
          if (cached) return cached;
          return new Response("Application is offline", {
            status: 503,
            statusText: "Offline",
            headers: { "Content-Type": "text/plain" }
          });
        })
    );
    return;
  }

  // 2. Static shell assets: cache-first with network fallback
  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(request).then((response) => {
        if (response && response.ok) {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
        }
        return response;
      });
    })
  );
});

self.addEventListener("message", (event) => {
  if (event.data === "skipWaiting") {
    self.skipWaiting();
  }
});
`;
}

/**
 * Default generated Service Worker script
 */
export const DEFAULT_SERVICE_WORKER = generateServiceWorker();

/**
 * Create a Service Worker config from PWA config
 */
export function createServiceWorkerConfig(pwaConfig: {
  version?: string;
  icons?: Array<{ src: string; sizes?: string }>;
  startUrl?: string;
  manifestPath?: string;
}): ServiceWorkerConfig {
  const assets = [
    pwaConfig.startUrl || "./mobile.html",
    "./bundle.js",
    pwaConfig.manifestPath || "./manifest.webmanifest",
    "./crosslink-mark.svg"
  ];

  if (pwaConfig.icons) {
    for (const icon of pwaConfig.icons) {
      if (icon.src && !assets.includes(icon.src)) {
        assets.push(icon.src);
      }
    }
  }

  return {
    version: pwaConfig.version || "1.0.0",
    precacheAssets: assets
  };
}
