/**
 * The script Crosslink injects into an application's mobile page.
 *
 * This is the piece that used to be copied into every project: register the
 * service worker, reload once when a new worker takes over so the install flow
 * cannot run against a stale cache, construct the bootstrap with the app's
 * metadata, and hand the developer an RPC channel once the device is trusted.
 *
 * The page it is injected into is the developer's own markup. It never renders
 * application UI, and the application never renders pairing, install, offline
 * or revoked UI — those are the bootstrap's, and this script is what connects
 * the two halves.
 */

/**
 * Metadata the host stamps into the page as `window.__CROSSLINK__`.
 *
 * Everything here comes from `createCrosslinkServer`'s `application` block, so
 * an application states its identity once, on the host, and the mobile page
 * inherits it rather than repeating it.
 */
export interface BootPayload {
  appId: string;
  appName: string;
  capabilities: string[];
  icon: string | null;
  accentColor: string;
  backgroundColor: string;
  textColor: string | null;
  appearance: "light" | "dark" | "auto";
  serviceWorkerUrl: string;
  /**
   * False when the page is served over plain HTTP to a non-loopback host. A
   * service worker cannot register there, so the cached offline shell does not
   * exist and the boot script says so in the console instead of registering a
   * worker that silently never installs.
   */
  secureContext: boolean;
  offlineTitle: string | null;
  offlineMessage: string | null;
  debuggingUrl: string;
}

/**
 * Generates the injected boot script.
 *
 * It is emitted as a string rather than served as a static file because most
 * of it is the application's own metadata; a static file would have to fetch
 * that first, which adds a round trip on the one page whose whole job is to
 * come up quickly on a phone that just scanned a code.
 */
export function renderBootScript(payload: BootPayload): string {
  return `/* Crosslink mobile bootstrap — generated by @crosslink/sdk-node */
(function () {
  var config = ${JSON.stringify(payload)};
  var SDK = window.CrosslinkSDK;
  if (!SDK) {
    console.error("[crosslink] browser SDK failed to load; the mobile bootstrap cannot start.");
    return;
  }

  /* A worker that claims the page after an update would otherwise leave the
     install flow running the previous bundle out of the old cache. Reloading
     once — guarded by sessionStorage so it cannot loop — puts the page on the
     version the new worker serves. */
  if ("serviceWorker" in navigator) {
    navigator.serviceWorker.addEventListener("controllerchange", function () {
      var key = "crosslink.sw-reloaded";
      try {
        if (!sessionStorage.getItem(key)) {
          sessionStorage.setItem(key, "1");
          location.reload();
        }
      } catch (err) {
        /* private mode with storage disabled: skip the reload rather than loop */
      }
    });
  }

  if (!config.secureContext) {
    console.warn(
      "[crosslink] This origin is not a secure context, so the browser will not register a " +
      "service worker. Pairing and RPC still work; the installable app and the cached " +
      "offline screen do not. Reach the host over https (a tunnel, or a certificate the " +
      "phone trusts) to enable them."
    );
  }

  var listeners = { connected: [], disconnected: [], state: [] };
  function emit(kind, detail) {
    for (var i = 0; i < listeners[kind].length; i += 1) {
      try {
        listeners[kind][i](detail);
      } catch (err) {
        console.error("[crosslink] listener failed", err);
      }
    }
    try {
      window.dispatchEvent(new CustomEvent("crosslink:" + kind, { detail: detail }));
    } catch (err) {
      /* CustomEvent is universally available in the browsers Crosslink targets;
         a failure here must not take the connection down. */
    }
  }

  var api = {
    appId: config.appId,
    appName: config.appName,
    rpc: null,
    client: null,
    state: "initializing",
    /** Runs now if already connected, then on every later reconnect. */
    onConnected: function (fn) {
      listeners.connected.push(fn);
      if (api.rpc) fn(api.rpc);
      return function () {
        listeners.connected = listeners.connected.filter(function (f) { return f !== fn; });
      };
    },
    onDisconnected: function (fn) {
      listeners.disconnected.push(fn);
      return function () {
        listeners.disconnected = listeners.disconnected.filter(function (f) { return f !== fn; });
      };
    },
    onStateChange: function (fn) {
      listeners.state.push(fn);
      return function () {
        listeners.state = listeners.state.filter(function (f) { return f !== fn; });
      };
    },
    /** Clears this device's Crosslink identity and starts pairing again. */
    reset: function () {
      return SDK.resetDeviceStorage().then(function () { location.reload(); });
    }
  };
  window.crosslink = api;

  /* The API object is published synchronously, from the document head, so a
     script anywhere in the developer's page can call \`crosslink.onConnected\`
     without worrying about load order. Starting the bootstrap is what waits for
     a body to render into. */
  function start() {
  var bootstrap = new SDK.CrosslinkMobileBootstrap({
    appId: config.appId,
    appName: config.appName,
    capabilities: config.capabilities,
    autoRegisterServiceWorker: config.secureContext,
    serviceWorkerUrl: config.serviceWorkerUrl,
    offline: {
      appName: config.appName,
      icon: config.icon || undefined,
      title: config.offlineTitle || undefined,
      message: config.offlineMessage || undefined,
      accentColor: config.accentColor,
      bgColor: config.backgroundColor,
      textColor: config.textColor || undefined,
      appearance: config.appearance,
      debuggingUrl: config.debuggingUrl
    },
    onboarding: {
      appName: config.appName,
      icon: config.icon || undefined,
      themeColor: config.accentColor
    },
    poweredBy: {
      placement: "top-left",
      offset: 8,
      size: 10,
      accentColor: config.accentColor,
      backgroundColor: config.backgroundColor
    },
    onAuthorized: function (rpc, client) {
      api.rpc = rpc;
      api.client = client;
      api.state = "authorized";
      document.documentElement.setAttribute("data-crosslink", "connected");
      emit("connected", rpc);
      emit("state", "authorized");
    },
    onUnauthorized: function () {
      api.rpc = null;
      api.state = "unauthorized";
      document.documentElement.setAttribute("data-crosslink", "disconnected");
      emit("disconnected", undefined);
      emit("state", "unauthorized");
    },
    onStateChange: function (state) {
      api.state = state;
      emit("state", state);
    }
  });
  api.bootstrap = bootstrap;

  bootstrap.start().catch(function (err) {
    console.error("[crosslink] mobile bootstrap failed to start", err);
  });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", start, { once: true });
  } else {
    start();
  }
})();
`;
}
